In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import pandas as pd

data = pd.read_csv('/content/drive/MyDrive/train.csv')
data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [ ]:
data.shape

(891, 12)

In [ ]:
data.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [ ]:
data["Sex_encoded"] = data["Sex"].apply(lambda x: 1 if x == "male" else 0)

In [ ]:
# Reemplaza los valores NaN en la columna de edad con la mediana
data["Age"].fillna(data["Age"].median(), inplace=True)


In [ ]:
data

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female  28.0      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  Sex_encoded  
0        0         A/5 21171   7.2500   NaN        S            1  
1        0          PC 17599  71.2833   C85        C            0  
2        0  STON/O2. 3101282   7.9250   NaN        S            0  
3        0            113803  53.1000  C123        S            0  
4        0            373450   8.0500   NaN        S            1  
..     ...               ...      ...   ...      ...          ...  
886      0            211536  13.0000   NaN        S            1  
887      0            112053  30.0000   B42        S            0  
888      2        W./C. 6607  23.4500   NaN        S            0  
889      0            111369  30.0000  C148        C            1  
890      0            370376   7.7500   NaN        Q            1  

[891 rows x 13 columns]

In [ ]:
X= data[[ 'Survived','Pclass', 'Sex_encoded', 'Age', 'SibSp',
       'Parch']].values

In [ ]:
print(X)

[[ 0.  3.  1. 22.  1.  0.]
 [ 1.  1.  0. 38.  1.  0.]
 [ 1.  3.  0. 26.  0.  0.]
 ...
 [ 0.  3.  0. 28.  1.  2.]
 [ 1.  1.  1. 26.  0.  0.]
 [ 0.  3.  1. 32.  0.  0.]]


In [ ]:
y = data['Survived'].values

In [ ]:
print(y)

[0 1 1 1 0 0 0 0 1 1 1 1 0 0 0 1 0 1 0 1 0 1 1 1 0 1 0 0 1 0 0 1 1 0 0 0 1
 0 0 1 0 0 0 1 1 0 0 1 0 0 0 0 1 1 0 1 1 0 1 0 0 1 0 0 0 1 1 0 1 0 0 0 0 0
 1 0 0 0 1 1 0 1 1 0 1 1 0 0 1 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 1 0 1 0
 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 1 0 0 0 0 1 0 0 1 0 0 0 0 1 1 0 0 0 1 0
 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 1 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 1
 0 1 1 0 0 1 0 1 1 1 1 0 0 1 0 0 0 0 0 1 0 0 1 1 1 0 1 0 0 0 1 1 0 1 0 1 0
 0 0 1 0 1 0 0 0 1 0 0 1 0 0 0 1 0 0 0 1 0 0 0 0 0 1 1 0 0 0 0 0 0 1 1 1 1
 1 0 1 0 0 0 0 0 1 1 1 0 1 1 0 1 1 0 0 0 1 0 0 0 1 0 0 1 0 1 1 1 1 0 0 0 0
 0 0 1 1 1 1 0 1 0 1 1 1 0 1 1 1 0 0 0 1 1 0 1 1 0 0 1 1 0 1 0 1 1 1 1 0 0
 0 1 0 0 1 1 0 1 1 0 0 0 1 1 1 1 0 0 0 0 0 0 0 1 0 1 1 0 0 0 0 0 0 1 1 1 1
 1 0 0 0 0 1 1 0 0 0 1 1 0 1 0 0 0 1 0 1 1 1 0 1 1 0 0 0 0 1 1 0 0 0 0 0 0
 1 0 0 0 0 1 0 1 0 1 1 0 0 0 0 0 0 0 0 1 1 0 1 1 1 1 0 0 1 0 1 0 0 1 0 0 1
 1 1 1 1 1 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 0 0 0 0 1 0 0 1 1 0 0 0 0 0 1 0
 0 0 1 1 0 1 0 0 1 0 0 0 

In [ ]:
y_train =y[:600]
y_val = y[600:]

X_train = X[:600]
X_val = X[600:]

In [ ]:
print(X_train)

[[ 0.  3.  1. 22.  1.  0.]
 [ 1.  1.  0. 38.  1.  0.]
 [ 1.  3.  0. 26.  0.  0.]
 ...
 [ 0.  3.  1. 49.  0.  0.]
 [ 0.  3.  1. 28.  0.  0.]
 [ 1.  1.  1. 49.  1.  0.]]


In [ ]:
print(y_train)

[0 1 1 1 0 0 0 0 1 1 1 1 0 0 0 1 0 1 0 1 0 1 1 1 0 1 0 0 1 0 0 1 1 0 0 0 1
 0 0 1 0 0 0 1 1 0 0 1 0 0 0 0 1 1 0 1 1 0 1 0 0 1 0 0 0 1 1 0 1 0 0 0 0 0
 1 0 0 0 1 1 0 1 1 0 1 1 0 0 1 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 1 0 1 0
 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 1 0 0 0 0 1 0 0 1 0 0 0 0 1 1 0 0 0 1 0
 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 1 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 1
 0 1 1 0 0 1 0 1 1 1 1 0 0 1 0 0 0 0 0 1 0 0 1 1 1 0 1 0 0 0 1 1 0 1 0 1 0
 0 0 1 0 1 0 0 0 1 0 0 1 0 0 0 1 0 0 0 1 0 0 0 0 0 1 1 0 0 0 0 0 0 1 1 1 1
 1 0 1 0 0 0 0 0 1 1 1 0 1 1 0 1 1 0 0 0 1 0 0 0 1 0 0 1 0 1 1 1 1 0 0 0 0
 0 0 1 1 1 1 0 1 0 1 1 1 0 1 1 1 0 0 0 1 1 0 1 1 0 0 1 1 0 1 0 1 1 1 1 0 0
 0 1 0 0 1 1 0 1 1 0 0 0 1 1 1 1 0 0 0 0 0 0 0 1 0 1 1 0 0 0 0 0 0 1 1 1 1
 1 0 0 0 0 1 1 0 0 0 1 1 0 1 0 0 0 1 0 1 1 1 0 1 1 0 0 0 0 1 1 0 0 0 0 0 0
 1 0 0 0 0 1 0 1 0 1 1 0 0 0 0 0 0 0 0 1 1 0 1 1 1 1 0 0 1 0 1 0 0 1 0 0 1
 1 1 1 1 1 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 0 0 0 0 1 0 0 1 1 0 0 0 0 0 1 0
 0 0 1 1 0 1 0 0 1 0 0 0 

In [ ]:
y_train = y_train.reshape(-1, 1)
y_val = y_val.reshape(-1, 1)


In [ ]:
y_train = y_train.ravel()
y_val = y_val.ravel()


In [ ]:
print("X_train shape:", X_train.shape)
print("y_train shape:", y_train.shape)


X_train shape: (600, 6)
y_train shape: (600,)


In [ ]:
import numpy as np

class NaiveBayes:
    def fit(self, X, y):
        self.X = X
        self.y = y
        self.classes = np.unique(y)
        self.parameters = []
        for i, c in enumerate(self.classes):
            X_where_c = X[np.where(y == c)]
            self.parameters.append({
                "mean": X_where_c.mean(axis=0),
                "var": X_where_c.var(axis=0),
                "prior": X_where_c.shape[0] / X.shape[0]
            })
    
    def predict(self, X):
        N, D = X.shape
        K = len(self.classes)
        P = np.zeros((N, K))
        for i, c in enumerate(self.classes):
            mean, var, prior = self.parameters[i].values()
            for d in range(D):
                P[:, i] += np.log(prior) - 0.5 * np.log(2 * np.pi * var[d]) - 0.5 * (X[:, d] - mean[d]) ** 2 / var[d]
        return self.classes[np.argmax(P, axis=1)]


In [ ]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(strategy='mean')
X_train_imputed = imputer.fit_transform(X_train)
X_val_imputed = imputer.transform(X_val)


In [ ]:
# Crea un objeto del modelo
gnb = NaiveBayes()


In [ ]:
# Entrena el modelo con los datos de entrenamiento
gnb.fit(X_train, y_train)



In [ ]:
# Haz predicciones en los datos de validación
y_pred = gnb.predict(X_val)


<ipython-input-18-033beb75880c>:24: RuntimeWarning: divide by zero encountered in log
  P[:, i] += np.log(prior) - 0.5 * np.log(2 * np.pi * var[d]) - 0.5 * (X[:, d] - mean[d]) ** 2 / var[d]
<ipython-input-18-033beb75880c>:24: RuntimeWarning: divide by zero encountered in true_divide
  P[:, i] += np.log(prior) - 0.5 * np.log(2 * np.pi * var[d]) - 0.5 * (X[:, d] - mean[d]) ** 2 / var[d]
<ipython-input-18-033beb75880c>:24: RuntimeWarning: invalid value encountered in true_divide
  P[:, i] += np.log(prior) - 0.5 * np.log(2 * np.pi * var[d]) - 0.5 * (X[:, d] - mean[d]) ** 2 / var[d]
<ipython-input-18-033beb75880c>:24: RuntimeWarning: invalid value encountered in subtract
  P[:, i] += np.log(prior) - 0.5 * np.log(2 * np.pi * var[d]) - 0.5 * (X[:, d] - mean[d]) ** 2 / var[d]


In [ ]:
# Calcular la precisión del modelo
from sklearn.metrics import accuracy_score
print("Precisión:", accuracy_score(y_val, y_pred))

Precisión: 0.6357388316151202


In [ ]:
survived = sum(y_pred == 1)
not_survived = sum(y_pred == 0)


In [ ]:
print("Survived:", survived)
print("Not Survived:", not_survived)


Survived: 0
Not Survived: 291
